src/objects/Association__c.object
<CustomObject>
    <fields>
        <fullName>Association__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Association</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Associations</relationshipLabel>
        <relationshipName>Associations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Legal_Case__c</referenceTo>
        <relationshipLabel>Associations</relationshipLabel>
        <relationshipName>Associations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Association</label>
    <nameField>
        <label>Association Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Associations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Member_Role__c.object
<CustomObject>
    <fields>
        <fullName>Association__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Association</label>
        <referenceTo>Association__c</referenceTo>
        <relationshipLabel>Member Roles</relationshipLabel>
        <relationshipName>Member_Roles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Legal_Case__c</referenceTo>
        <relationshipLabel>Member Roles</relationshipLabel>
        <relationshipName>Member_Roles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Member</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Member Roles</relationshipLabel>
        <relationshipName>Member_Roles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Role</valueSetName>
        </valueSet>
    </fields>
    <label>Member Role</label>
    <nameField>
        <label>Member Role Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Member Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/Role.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Doctor</fullName>
    </customValue>
    <customValue>
        <fullName>Family Member</fullName>
    </customValue>
    <customValue>
        <fullName>Insurance Agent</fullName>
    </customValue>
    <customValue>
        <fullName>Victim</fullName>
    </customValue>
    <masterLabel>Role</masterLabel>
</GlobalValueSet>

src/classes/CaseServices.cls
public with sharing class CaseServices {
    public static List<Association__c> getRelatedAssociations(Id caseId) {
        if(caseId == null) {
            return new List<Association__c>();
        }

        return [
            SELECT Id,
                    Name,
                    Association__c,
                    Association__r.Name,
                    Association__r.Industry,
                    OwnerId,
                    Owner.Name,
                    Case__c
            FROM Association__c
            WHERE Case__c = :caseId
        ];
    }

    public static List<Association__c> getRelatedAssociationsWithRoles(Id caseId) {
        if(caseId == null) {
            return new List<Association__c>();
        }

        return [
                SELECT Id,
                        Name,
                        Association__c,
                        Association__r.Name,
                        Association__r.Industry,
                        OwnerId,
                        Owner.Name,
                        Case__c,
                (
                        SELECT Id,
                                Name,
                                Role__c,
                                Member__c,
                                Member__r.Name,
                                Association__c
                        FROM Member_Roles__r
                )
                FROM Association__c
                WHERE Case__c = :caseId
        ];
    }

    public static List<Member_Role__c> getRelatedMemberRoles(Id caseId) {
        if(caseId == null) {
            return new List<Member_Role__c>();
        }

        return [
                SELECT Id,
                        Name,
                        Role__c,
                        Member__c,
                        Member__r.Name,
                        Association__c,
                        Association__r.Name,
                        Association__r.Case__c
                FROM Member_Role__c
                WHERE Association__r.Case__c = :caseId
        ];
    }
}