src/objects/Association__c.object
<CustomObject>
    <fields>
        <fullName>Association__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Association</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Associations</relationshipLabel>
        <relationshipName>Associations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Association</label>
    <nameField>
        <label>Association Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Associations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Legal_Case__c.object
<CustomObject>
    <label>Legal Case</label>
    <nameField>
        <label>Legal Case Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Legal Cases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Member_Role__c.object
<CustomObject>
    <fields>
        <fullName>Association__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Association</label>
        <referenceTo>Association__c</referenceTo>
        <relationshipLabel>Member Roles</relationshipLabel>
        <relationshipName>Member_Roles</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Member Role</label>
    <nameField>
        <label>Member Role Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Member Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestDataFactory.cls
public with sharing class TestDataFactory {
    // Returns a list of SObjects with all fields designated required filled
    public static List<SObject> createSObjects(String sObjectName, Integer amount) {
        List<Map<String,Object>> fieldMaps = TestDataService.populateMandatoryFields(sObjectName);
        Map<String,Object> fieldToValue = fieldMaps[0];
        Map<String,Integer> incrementFieldToLength = (Map<String,Integer>)fieldMaps[1];

        return TestDataService.genericFactory(amount, sObjectName, fieldToValue, incrementFieldToLength);
    }

    public static List<Account> createAccounts(Integer amount) {
        return (List<Account>)createSObjects('Account', amount);
    }

    public static List<Contact> createContacts(Integer amount) {
        return (List<Contact>)createSObjects('Contact', amount);
    }

    public static List<Legal_Case__c> createLegalCases(Integer amount) {
        return (List<Legal_Case__c>)createSObjects('Legal_Case__c', amount);
    }

    public static List<Association__c> createAssociations(Integer amount) {
        return (List<Association__c>)createSObjects('Association__c', amount);
    }

    public static List<Member_Role__c> createMemberRoles(Integer amount) {
        return (List<Member_Role__c>)createSObjects('Member_Role__c', amount);
    }
}